###
# Avoid syncing from prometheus/prometheus: no_prometheus_repo_sync
###
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      cargo-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      cargo-major:
        patterns:
          - "*"
        update-types:
          - "major"
    open-pull-requests-limit: 2
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 1
    cooldown:
      default-days: 7
